/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import javax.swing.ButtonGroup;

/**
 *
 * @author rishu
 */
public class PbtBankDetails extends javax.swing.JDialog {

    PbtAadharDetails aadharob;
    int hhsno;
    PbtPersonDashboard obperson;
    ButtonGroup bg1, bg2;
    ParabitDBC db;
    String net, mob;
    public PbtBankDetails(PbtPersonDashboard ob, PbtAadharDetails nob, int hhno, boolean in) {
        super(ob, true);
        initComponents();
        hhsno = hhno;
        aadharob = nob;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg1.add(rbmobyes);
        bg1.add(rbmobno);
        bg2.add(rbnetyes);
        bg2.add(rbnetno);
        
        if (in == true)
        {
            incomp();
        }
    }
    
    public PbtBankDetails(PbtPersonDashboard ob, int hhno, boolean in) {
        super(ob, true);
        setTitle("Bank Details");
        initComponents();
        hhsno = hhno;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg1.add(rbmobyes);
        bg1.add(rbmobno);
        bg2.add(rbnetyes);
        bg2.add(rbnetno);
        
        if (in == true)
        {
            incomp();
        }
    }
    
    public void incomp()
    {
        try
        {
            tfifsc.setText(obperson.db.rs2.getString("IFSC"));
            tfbank.setText(obperson.db.rs2.getString("BankAccNo"));
            if (obperson.db.rs2.getString("NetBank").equals("Y"))
            {
                rbnetyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("NetBank").equals("N"))
            {
                rbnetno.setSelected(true);
            }
            
            if (obperson.db.rs2.getString("MobBank").equals("Y"))
            {
                rbmobyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("MobBank").equals("N"))
            {
                rbmobno.setSelected(true);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfifsc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfbank = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbmobyes = new javax.swing.JRadioButton();
        rbnetyes = new javax.swing.JRadioButton();
        rbnetno = new javax.swing.JRadioButton();
        rbmobno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("IFSC Code:");

        jLabel2.setText("Bank Account No.:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel9.setText("BANK DETAILS");

        jLabel3.setText("Net Banking:");

        jLabel4.setText("Mobile Banking:");

        rbmobyes.setText("Yes");

        rbnetyes.setText("Yes");

        rbnetno.setText("No");

        rbmobno.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rbnetyes)
                        .addGap(21, 21, 21)
                        .addComponent(rbnetno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rbmobyes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbmobno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfbank, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbank, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbmobyes)
                    .addComponent(rbnetno)
                    .addComponent(rbnetyes)
                    .addComponent(rbmobno))
                .addGap(38, 38, 38)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if (rbnetyes.isSelected())
        {
            net = "Y";
        }
        else
        {
            net = "N";
        }
        if (rbmobyes.isSelected())
        {
            mob = "Y";
        }
        else
        {
            mob = "N";
        }
        String qry = "UPDATE pbtcensus_household SET IFSC = '"+tfifsc.getText()+"',BankAccNo = '"+tfbank.getText()+"',NetBank = '"+net+"',"
                + "MobBank = '"+mob+"' WHERE HH_SNo = "+hhsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.dispose();
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtBankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtBankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtBankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtBankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHomedashboard obj = new PbtHomedashboard(0, new PbtLoginData());
                PbtBankDetails dialog = new PbtBankDetails(new PbtPersonDashboard(obj, 0), 0, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbmobno;
    private javax.swing.JRadioButton rbmobyes;
    private javax.swing.JRadioButton rbnetno;
    private javax.swing.JRadioButton rbnetyes;
    private javax.swing.JTextField tfbank;
    private javax.swing.JTextField tfifsc;
    // End of variables declaration//GEN-END:variables
}
