/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseListener;
/**
 *
 * @author rishu
 */
public class PbtCensus extends javax.swing.JDialog implements MouseListener {

    PbtLoginData oblogin;
    PbtEnumDashboard enumdash;
    ParabitDBC db;
    public PbtCensus(PbtEnumDashboard nob, PbtLoginData ob) {
        super(nob, true);
        setTitle("Census");
        initComponents();
        this.setLocationRelativeTo(nob);
        oblogin = ob;
        enumdash = nob;
        db = new ParabitDBC();
        loadTable();
        
        townvill.addMouseListener(this);
        
        btnhouselist.setEnabled(false);
        btnincomplete.setEnabled(false);
    }

    void loadTable()
    {
        String qry = "SELECT * FROM pbtempschedule WHERE CEID = '"+oblogin.ceid+"'";
        try         
        {
            db.rs1 = db.stm.executeQuery(qry);
            DefaultTableModel tm = (DefaultTableModel)townvill.getModel();
            tm.setRowCount(0);
            
            while(db.rs1.next())
            {
                int tp = db.rs1.getInt("PopulationAlloted");
                int wd = db.rs1.getInt("WorkDone");
                int pp = tp - wd;
                Object o[] = {db.rs1.getString("City_Vill"), tp, wd, pp};
                tm.addRow(o);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhouselist = new javax.swing.JButton();
        btnindustry = new javax.swing.JButton();
        btnlandres = new javax.swing.JButton();
        btnincomplete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        townvill = new javax.swing.JTable();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnhouselist.setText("Houselisting");
        btnhouselist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhouselistActionPerformed(evt);
            }
        });

        btnindustry.setText("Industry");
        btnindustry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnindustryActionPerformed(evt);
            }
        });

        btnlandres.setText("Land Resource");
        btnlandres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlandresActionPerformed(evt);
            }
        });

        btnincomplete.setText("Incomplete");
        btnincomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincompleteActionPerformed(evt);
            }
        });

        townvill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Town/Village", "Total Population", "Population Completed", "Population Pending"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(townvill);

        btnback.setText("<-- GO BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnhouselist, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnincomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnindustry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnlandres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnincomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhouselist, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnindustry, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlandres, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhouselistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhouselistActionPerformed
        PbtHouseUse ob = new PbtHouseUse(enumdash, oblogin);
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_btnhouselistActionPerformed

    private void btnincompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincompleteActionPerformed
        PbtIncompleteCensus ob = new PbtIncompleteCensus(this);
        ob.setLocationRelativeTo(this);
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_btnincompleteActionPerformed

    private void btnindustryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnindustryActionPerformed
        PbtIndustry ob = new PbtIndustry(this);
        ob.setLocationRelativeTo(this);
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_btnindustryActionPerformed

    private void btnlandresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlandresActionPerformed
        PbtLand ob = new PbtLand(this);
        ob.setLocationRelativeTo(this);
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_btnlandresActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        enumdash.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtCensus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtCensus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtCensus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtCensus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PbtCensus dialog = new PbtCensus(new PbtEnumDashboard(new PbtLoginData()), new PbtLoginData());
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhouselist;
    private javax.swing.JButton btnincomplete;
    private javax.swing.JButton btnindustry;
    private javax.swing.JButton btnlandres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable townvill;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 1)
        {
            int r = townvill.getSelectedRow();
            if(townvill.isRowSelected(r) == true)
            {
                btnhouselist.setEnabled(true);
                btnincomplete.setEnabled(true);
            }
            else
            {
                btnhouselist.setEnabled(false);
                btnincomplete.setEnabled(false);
                btnindustry.setEnabled(false);
                btnlandres.setEnabled(false);
            }
            String town = townvill.getValueAt(r, 0).toString();
            oblogin.town = town;
        }
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
