/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishu
 */
public class PbtEnumDashboard extends javax.swing.JFrame {

    PbtLoginData oblogin;
    ParabitDBC db;
    public PbtEnumDashboard(PbtLoginData nob) {
        setTitle("Dashboard");
        initComponents();
        oblogin = nob;
        db = new ParabitDBC();
        String qry = "SELECT * FROM pbtnotification WHERE (RecieverCeId = '" + oblogin.ceid + "' AND MsgStatus = 0) OR (NotType = 3 AND ((SenderCeId IN (SELECT CRepEmpID FROM pbtemployeetable2 WHERE AreaCity = '"+oblogin.city+"')) OR (SenderCeID = '93425')) AND SenderCeID != '"+oblogin.ceid+"' AND ReadTime >= '"+LocalDate.now()+"') OR (NotType = 2 AND RecieverCeID IN (SELECT CRepEmpID FROM pbtemployeetable2 WHERE AreaCity = '"+oblogin.city+"') AND ReadTime >= '"+LocalDate.now()+"') ORDER BY Time DESC";
        String qry2 = "SELECT SUM(PopulationAlloted), SUM(WorkDone) FROM pbtempschedule WHERE CEID = '" + oblogin.ceid + "'";
        String qry3 = "SELECT EmpName FROM pbtemployeetable2 WHERE CEID = '" + oblogin.ceid + "'";
        try         
        {
            db.rs1 = db.stm.executeQuery(qry);
            DefaultTableModel tm = (DefaultTableModel)notif.getModel();
            tm.setRowCount(0);
            
            while(db.rs1.next())
            {
                Object o[] = {db.rs1.getString("SenderCeid"), db.rs1.getTimestamp("Time").toString().substring(0, 19), db.rs1.getString("Message"),
                              db.rs1.getInt("NotId"), db.rs1.getInt("NotType")};
                tm.addRow(o);
            }
            db.rs2 = db.stm.executeQuery(qry2);
            int total = 0;
            int completed = 0;
            int pending = 0;
            if (db.rs2.next())
            {
                total = db.rs2.getInt(1);
                completed = db.rs2.getInt(2);
                pending = total - completed;
            }
            lpopalloted.setText("Population Alloted : "+ total);
            lcompleted.setText("Completed : " + completed);
            lpending.setText("Pending : " + pending);
            db.rs3 = db.stm.executeQuery(qry3);
            db.rs3.next();
            lwelcome.setText("Welcome, "+db.rs3.getString(1));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncensus = new javax.swing.JButton();
        btnnotif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notif = new javax.swing.JTable();
        btnlogout = new javax.swing.JButton();
        lwelcome = new javax.swing.JLabel();
        lpending = new javax.swing.JLabel();
        lpopalloted = new javax.swing.JLabel();
        lcompleted = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncensus.setText("Census");
        btncensus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncensusActionPerformed(evt);
            }
        });

        btnnotif.setText("Notification");
        btnnotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotifActionPerformed(evt);
            }
        });

        jLabel1.setText("Notifications:");

        notif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender CEID", "Time", "Message", "NotID", "NotType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(notif);

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        lwelcome.setText("Welcome");

        lpending.setText("Pending:");

        lpopalloted.setText("Population Alloted:");

        lcompleted.setText("Completed:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btncensus, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(btnnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lpopalloted, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(lcompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(lpending, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)))
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lpending, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpopalloted, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncensus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncensusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncensusActionPerformed
    PbtCensus ob = new PbtCensus(this, oblogin);
    this.setVisible(false);
    ob.setVisible(true);
    }//GEN-LAST:event_btncensusActionPerformed

    private void btnnotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotifActionPerformed
        PbtNotification obnotif = new PbtNotification(this, true, oblogin);
        obnotif.setVisible(true);
    }//GEN-LAST:event_btnnotifActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtEnumDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtEnumDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtEnumDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtEnumDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PbtEnumDashboard ob = new PbtEnumDashboard(new PbtLoginData());
                ob.setVisible(true);
                ob.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncensus;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnotif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lcompleted;
    private javax.swing.JLabel lpending;
    private javax.swing.JLabel lpopalloted;
    private javax.swing.JLabel lwelcome;
    private javax.swing.JTable notif;
    // End of variables declaration//GEN-END:variables
}
