/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import javax.swing.ButtonGroup;

/**
 *
 * @author rishu
 */
public class PbtEducationDetails extends javax.swing.JDialog {

    int hhsno;
    PbtAadharDetails aadharob;
    PbtPersonDashboard obperson;
    ParabitDBC db;
    String lit, nccnss, currentedu;
    ButtonGroup bg1, bg2;
    public PbtEducationDetails(PbtPersonDashboard ob, PbtAadharDetails nob, int hhno, boolean in) {
        super(ob, true);
        setTitle("Education Details");
        initComponents();
        hhsno = hhno;
        aadharob = nob;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg1.add(rbyes);
        bg1.add(rbno);
        bg2.add(rbliterate);
        bg2.add(rbiliterate);
        cedustatus.addItem("School");
        cedustatus.addItem("College");
        cedustatus.addItem("Vocational");
        cedustatus.addItem("Special Institute for disabled");
        cedustatus.addItem("Literacy Status");
        cedustatus.addItem("Other Institution");
        cedustatus.addItem("Attended Before");
        cedustatus.addItem("Never Attended");
        
        if (in == true)
        {
            incomp();
        }
        
    }
    
    public PbtEducationDetails(PbtPersonDashboard ob, int hhno, boolean in)
    {
        super(ob, true);
        initComponents();
        hhsno = hhno;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg1.add(rbyes);
        bg1.add(rbno);
        bg2.add(rbliterate);
        bg2.add(rbiliterate);
        cedustatus.addItem("School");
        cedustatus.addItem("College");
        cedustatus.addItem("Vocational");
        cedustatus.addItem("Special Institute for disabled");
        cedustatus.addItem("Literacy Status");
        cedustatus.addItem("Other Institution");
        cedustatus.addItem("Attended Before");
        cedustatus.addItem("Never Attended");
        if (in == true)
        {
            incomp();
        }
    }

    public void incomp()
    {
        try
        {
            if (obperson.db.rs2.getString("LitStatus").equals("Y"))
            {
                rbliterate.setSelected(true);
            }
            else if (obperson.db.rs2.getString("LitStatus").equals("N"))
            {
                rbiliterate.setSelected(true);
            }
            tfmothertongue.setText(obperson.db.rs2.getString("MTongue"));
            tfrwlang.setText(obperson.db.rs2.getString("RWLang"));
            tfhomelang.setText(obperson.db.rs2.getString("HomeLang"));
            tfcurrinstitute.setText(obperson.db.rs2.getString("CInstNmCity"));
            tftechdegree.setText(obperson.db.rs2.getString("TechDeg"));
            tfcurrinstitutetype.setText(obperson.db.rs2.getString("CInstType"));
            tfnontechdegree.setText(obperson.db.rs2.getString("NonTechDeg"));
            if (obperson.db.rs2.getString("NCCNSS").equals("Y"))
            {
                rbyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("NCCNSS").equals("N"))
            {
                rbno.setSelected(true);
            }
            cedustatus.setSelectedIndex(Integer.parseInt(obperson.db.rs2.getString("CEduStatus")));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tftechdegree = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfcurrinstitute = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfnontechdegree = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfbtnsave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbliterate = new javax.swing.JRadioButton();
        rbyes = new javax.swing.JRadioButton();
        rbno = new javax.swing.JRadioButton();
        rbiliterate = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        tfmothertongue = new javax.swing.JTextField();
        tfrwlang = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfhomelang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfcurrinstitutetype = new javax.swing.JTextField();
        cedustatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Literacy Status:");

        jLabel7.setText("NCCNSS:");

        jLabel2.setText("Current Institute Name With City:");

        jLabel3.setText("Non Technical Degree:");

        jLabel9.setText("EDUCATION DETAILS");

        tfbtnsave.setText("Save");
        tfbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbtnsaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Current Education Status:");

        jLabel6.setText("Technical Degree:");

        rbliterate.setText("Literate");

        rbyes.setText("Yes");

        rbno.setText("No");

        rbiliterate.setText("Iliterate");

        jLabel24.setText("Mother Tongue:");

        jLabel25.setText("Read Write Language:");

        jLabel26.setText("Home Language:");

        jLabel4.setText("Current Institute Type:");

        cedustatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { null }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfcurrinstitutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(tftechdegree, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfbtnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfhomelang, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rbliterate)
                                .addGap(18, 18, 18)
                                .addComponent(rbiliterate)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfmothertongue, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(tfrwlang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cedustatus, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcurrinstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfnontechdegree, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rbyes)
                        .addGap(18, 18, 18)
                        .addComponent(rbno)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbliterate)
                    .addComponent(rbiliterate)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmothertongue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfrwlang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfhomelang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfcurrinstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedustatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfcurrinstitutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tftechdegree, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfnontechdegree, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rbyes)
                    .addComponent(rbno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfbtnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbtnsaveActionPerformed
        if (rbyes.isSelected())
        {
            nccnss = "Y";
        }
        if (rbno.isSelected())
        {
            nccnss = "N";
        }
        if (rbliterate.isSelected())
        {
            lit = "Y";
        }
        if (rbiliterate.isSelected())
        {
            lit = "N";
        }
           
        currentedu = cedustatus.getSelectedIndex()+"";
                
        String qry = "UPDATE pbtcensus_household SET LitStatus = '"+lit+"',CEduStatus = '"+currentedu+"',CInstNmCity = '"+tfcurrinstitute.getText()+"',"
                + "TechDeg = '"+tftechdegree.getText()+"',NonTechDeg = '"+tfnontechdegree.getText()+"',NCCNSS = '"+nccnss+"',"
                + "MTongue = '"+tfmothertongue.getText()+"',RWLang = '"+tfrwlang.getText()+"',HomeLang = '"+tfhomelang.getText()+"',"
                + "CInstType = '"+tfcurrinstitutetype.getText()+"' WHERE HH_SNo = "+hhsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.dispose();
    }//GEN-LAST:event_tfbtnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtEducationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtEducationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtEducationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtEducationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHomedashboard obj = new PbtHomedashboard(0, new PbtLoginData());
                PbtEducationDetails dialog = new PbtEducationDetails(new PbtPersonDashboard(obj, 0), 0, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cedustatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbiliterate;
    private javax.swing.JRadioButton rbliterate;
    private javax.swing.JRadioButton rbno;
    private javax.swing.JRadioButton rbyes;
    private javax.swing.JButton tfbtnsave;
    private javax.swing.JTextField tfcurrinstitute;
    private javax.swing.JTextField tfcurrinstitutetype;
    private javax.swing.JTextField tfhomelang;
    private javax.swing.JTextField tfmothertongue;
    private javax.swing.JTextField tfnontechdegree;
    private javax.swing.JTextField tfrwlang;
    private javax.swing.JTextField tftechdegree;
    // End of variables declaration//GEN-END:variables
}
