/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

/**
 *
 * @author rishu
 */
public class PbtHLAppliance extends javax.swing.JDialog {

    /**
     * Creates new form HL4
     */
    int hlsno;
    ParabitDBC db;
    String radio, fm, ref, ch, t;
    int tv, coolheat, pc, tele, tvsignal, mobile;
    public PbtHLAppliance(PbtHouselisting ob, int hlno) {
        super(ob, true);
        setTitle("Appliance");
        initComponents();
        hlsno = hlno;
        db = new ParabitDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioyes = new javax.swing.JRadioButton();
        radiono = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        fmyes = new javax.swing.JRadioButton();
        fmno = new javax.swing.JRadioButton();
        tftv = new javax.swing.JTextField();
        btntv = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbtv = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        refyes = new javax.swing.JRadioButton();
        refno = new javax.swing.JRadioButton();
        tfcoolheat = new javax.swing.JTextField();
        btncoolheat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfpc = new javax.swing.JTextField();
        btnpc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbmobile = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        tfref = new javax.swing.JTextField();
        tftele = new javax.swing.JTextField();
        btntele = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Appliance Details");

        jLabel2.setText("Radio Available:");

        buttonGroup1.add(radioyes);
        radioyes.setText("Yes");

        buttonGroup1.add(radiono);
        radiono.setText("No");

        jLabel3.setText("FM Available:");

        buttonGroup2.add(fmyes);
        fmyes.setText("Yes");

        buttonGroup2.add(fmno);
        fmno.setText("No");

        btntv.setText("Select");
        btntv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntvActionPerformed(evt);
            }
        });

        jLabel6.setText("No. Of TV:");

        jLabel10.setText("TV Signal:");

        jcbtv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DDFreeDish", "Cable", "DTH", "WebTV", "None" }));

        jLabel4.setText("Refrigerator Available:");

        buttonGroup3.add(refyes);
        refyes.setText("Yes");

        buttonGroup3.add(refno);
        refno.setText("No");

        btncoolheat.setText("Select");
        btncoolheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoolheatActionPerformed(evt);
            }
        });

        jLabel7.setText("CoolHeat Facility:");

        btnpc.setText("Select");
        btnpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpcActionPerformed(evt);
            }
        });

        jLabel8.setText("No. Of PC:");

        jLabel11.setText("TeleBroadband:");

        jcbmobile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feature Phone", "Smart Phone", "Telephone", "Feature Phone, Telephone", "Feature Phone, Smart Phone", "Smart Phone,Telephone", "Feature Phone, Smart Phone, Telephone" }));

        jLabel9.setText("Mobile:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btntele.setText("Select");
        btntele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(152, 152, 152))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioyes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radiono)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(fmyes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fmno)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tftv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(btntv))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfpc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnpc)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(49, 49, 49)
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jcbtv, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(tfcoolheat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btncoolheat))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(tftele, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btntele)))
                                        .addGap(32, 32, 32))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfref, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioyes)
                    .addComponent(radiono)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fmyes)
                    .addComponent(fmno))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbtv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refyes)
                    .addComponent(refno)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcoolheat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncoolheat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfref, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftele, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntele, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntvActionPerformed
        PbtTV obj = new PbtTV(this);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
        System.out.println(tv);
    }//GEN-LAST:event_btntvActionPerformed

    private void btncoolheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoolheatActionPerformed
        PbtCoolHeat obj = new PbtCoolHeat(this);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
        tfcoolheat.setText(ch);
        System.out.println(coolheat);
    }//GEN-LAST:event_btncoolheatActionPerformed

    private void btnpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpcActionPerformed
        PbtPC obj = new PbtPC(this);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
        System.out.println(pc);
    }//GEN-LAST:event_btnpcActionPerformed

    private void btnteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteleActionPerformed
        PbtTelebroadband obj = new PbtTelebroadband(this);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
        tftele.setText(t);
        System.out.println(tele);
    }//GEN-LAST:event_btnteleActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       
        if (jcbtv.getSelectedItem().equals("DDFreeDish"))
        {
           tvsignal = 1; 
        }
        else if (jcbtv.getSelectedItem().equals("Cable"))
        {
            tvsignal = 2;
        }
        else if (jcbtv.getSelectedItem().equals("DTH"))
        {
            tvsignal = 3;
        }
        else if (jcbtv.getSelectedItem().equals("WebTV"))
        {
            tvsignal = 4;
        }
        else
        {
            tvsignal = 5;
        }
        
        if (jcbmobile.getSelectedItem().equals("Feature Phone"))
        {
           mobile = 1; 
        }
        else if (jcbtv.getSelectedItem().equals("Smart Phone"))
        {
            mobile = 2;
        }
        else if (jcbtv.getSelectedItem().equals("Telephone"))
        {
            mobile = 3;
        }
        else if (jcbtv.getSelectedItem().equals("Feature Phone, Telephone"))
        {
            mobile = 4;
        }
        else if (jcbtv.getSelectedItem().equals("Feature Phone, Smart Phone"))
        {
            mobile = 5;
        }
        else if (jcbtv.getSelectedItem().equals("Smart Phone,Telephone"))
        {
            mobile = 6;
        }
        else
        {
            mobile = 7;
        }
        if (refyes.isSelected())
        {
            ref = "Y";
        }
        else
        {
            ref = "N";
        }
        if (fmyes.isSelected())
        {
            fm = "Y";
        }
        else
        {
            fm = "N";
        }
        if (radioyes.isSelected())
        {
            radio = "Y";
        }
        else
        {
            radio = "N";
        }
        String qry = "UPDATE pbtcensus_houselisting SET Radio = '"+radio+"',FM = '"+fm+"',TV = '"+tftv.getText()+tv+"',TVSig = "+tvsignal+""
                + ",Refrigerator = '"+ref+tfref.getText()+"',CoolHeatFact = "+coolheat+",PC = '"+tfpc.getText()+pc+"',TeleBroadBand = "+tele+""
                + ",Mob = "+mobile+" WHERE HL_SNo = "+hlsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.dispose();
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHLAppliance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHLAppliance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHLAppliance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHLAppliance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHLAppliance dialog = new PbtHLAppliance(new PbtHouselisting(0, new PbtLoginData()), 0);
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoolheat;
    private javax.swing.JButton btnpc;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntele;
    private javax.swing.JButton btntv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton fmno;
    private javax.swing.JRadioButton fmyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbmobile;
    private javax.swing.JComboBox<String> jcbtv;
    private javax.swing.JRadioButton radiono;
    private javax.swing.JRadioButton radioyes;
    private javax.swing.JRadioButton refno;
    private javax.swing.JRadioButton refyes;
    private javax.swing.JTextField tfcoolheat;
    private javax.swing.JTextField tfpc;
    private javax.swing.JTextField tfref;
    private javax.swing.JTextField tftele;
    private javax.swing.JTextField tftv;
    // End of variables declaration//GEN-END:variables
}
