/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

/**
 *
 * @author rishu
 */
public class PbtHLOther extends javax.swing.JDialog {

    /**
     * Creates new form HL6
     */
    ParabitDBC db, db1;
    int hlsno, bike, reg2wheel, reg4wheel, commvehicles;
    String domanimals, petanimals, parking;
    public PbtHLOther(PbtHouselisting ob, int hlno) {
        super(ob, true);
        setTitle("Other");
        initComponents();
        hlsno = hlno;
        db = new ParabitDBC();
        db1 = new ParabitDBC(1);
        String qry = "SELECT UID FROM pbtcensus_household WHERE HL_SNo = " + hlno;
        
        try
        {
            db.rs1 = db.stm.executeQuery(qry);
            while (db.rs1.next())
            {
                String qry2 = "SELECT Count(ANo) FROM pbtregistrationcertificate WHERE ANo = '"+db.rs1.getString(1)+"' AND VehicleType = '2'";
                db1.rs1 = db1.stm.executeQuery(qry2);
                if (db1.rs1.next())
                {
                    reg2wheel += db1.rs1.getInt(1);
                }
                String qry3 = "SELECT Count(ANo) FROM pbtregistrationcertificate WHERE ANo = '"+db.rs1.getString(1)+"' AND VehicleType = '4'";
                db1.rs2 = db1.stm.executeQuery(qry3);
                if (db1.rs2.next())
                {
                    reg4wheel += db1.rs2.getInt(1);
                }
                String qry4 = "SELECT Count(ANo) FROM pbtregistrationcertificate WHERE ANo = '"+db.rs1.getString(1)+"' AND VehicleType IS null";
                db1.rs3= db1.stm.executeQuery(qry4);
                if (db1.rs3.next())
                {
                    commvehicles += db1.rs3.getInt(1);
                }
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        tfreg2wheel.setText(reg2wheel+"");
        tfreg4wheel.setText(reg4wheel+"");
        commvehicle.setValue(commvehicles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tftrees = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfprotectedtrees = new javax.swing.JTextField();
        btndom = new javax.swing.JButton();
        tf = new javax.swing.JLabel();
        tfpetno = new javax.swing.JTextField();
        btnpet = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        commvehicle = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        parkingyes = new javax.swing.JRadioButton();
        parkingno = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tflift = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfescalator = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfhelipad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfreg2wheel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfreg4wheel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taexpectation = new javax.swing.JTextArea();
        btnsave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tadom = new javax.swing.JTextArea();
        jcb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Other Details");

        jLabel2.setText("No. Of Trees:");

        jLabel3.setText("No. Of Protected Trees:");

        btndom.setText("Select");
        btndom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndomActionPerformed(evt);
            }
        });

        tf.setText("Type Of Domestic Animals With No.:");

        btnpet.setText("Select");
        btnpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpetActionPerformed(evt);
            }
        });

        jLabel9.setText("No. Of Pet Animals:");

        jLabel10.setText("Bicycle:");

        jLabel4.setText("Total Number Of Commercial Vehicle:");

        parkingyes.setText("Yes");

        parkingno.setText("No");

        jLabel5.setText("Parking Facility:");

        jLabel6.setText("Lift:");

        jLabel7.setText("Escalator:");

        jLabel11.setText("Helipad:");

        jLabel12.setText("Registered 2 Wheeler:");

        jLabel13.setText("Registered 4 Wheeler:");

        jLabel14.setText("Expectations:");

        taexpectation.setColumns(20);
        taexpectation.setRows(5);
        jScrollPane1.setViewportView(taexpectation);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        tadom.setColumns(20);
        tadom.setRows(5);
        jScrollPane2.setViewportView(tadom);

        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"none", "Mountain Bike",
            "Hybrid/Comfort Bike",
            "Road Bike",
            "Electric Bike",
            "Gravel Bike",
            "Touring Bike",
            "Mountain Bike,Hybrid/Comfort Bike",
            "Mountain Bike, Road Bike",
            "Mountain Bike,Electric Bike",
            "Mountain Bike,Gravel Bike",
            "Mountain Bike,Touring Bike",
            "Hybrid/Comfort Bike,Road Bike",
            "Hybrid/Comfort Bike,Electric Bike",
            "Hybrid/Comfort Bike,Gravel Bike",
            "Hybrid/Comfort Bike, Touring Bike",
            "Road Bike,Electric Bike",
            "Road Bike,Gravel Bike",
            "Road Bike,Touring Bike",
            "Electric Bike,Gravel Bike",
            "Electric Bike,Touring Bike",
            "Gravel Bike,Touring Bike"}));
jcb.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcbActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(53, 53, 53)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2)
                    .addGap(18, 18, 18)
                    .addComponent(btndom)
                    .addGap(25, 25, 25)
                    .addComponent(jLabel9)
                    .addGap(13, 13, 13)
                    .addComponent(tfpetno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnpet)
                    .addGap(49, 49, 49))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tflift, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfescalator, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(112, 112, 112)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfhelipad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(250, 250, 250)
                                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tftrees, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tfprotectedtrees, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(tfreg2wheel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(tfreg4wheel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(91, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addGap(18, 18, 18)
                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jLabel4)
                    .addGap(17, 17, 17)
                    .addComponent(commvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addComponent(parkingyes)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(parkingno)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tftrees, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfprotectedtrees, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfreg2wheel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfreg4wheel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfpetno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnpet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(commvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parkingyes)
                                    .addComponent(parkingno))))))
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tflift, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfescalator, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfhelipad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(34, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53))))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndomActionPerformed
       PbtDomAnimals ob = new PbtDomAnimals(this);
       ob.setLocationRelativeTo(this);
       ob.setVisible(true);
       System.out.println(domanimals);
       tadom.setText(domanimals);
    }//GEN-LAST:event_btndomActionPerformed

    private void btnpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpetActionPerformed
        PbtPetAnimals ob = new PbtPetAnimals(this);
       ob.setLocationRelativeTo(this);
       ob.setVisible(true);
       System.out.println(petanimals);
    }//GEN-LAST:event_btnpetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if (parkingyes.isSelected())
        {
            parking = "Y";
        }
        else
        {
            parking = "N";
        }
        
        String pet = tfpetno.getText()+petanimals;
        String qry = "UPDATE pbtcensus_houselisting SET NoOfTrees = '"+tftrees.getText()+"',NoOfProtTrees = '"+tfprotectedtrees.getText()+"',R2Wheel = "+tfreg2wheel.getText()+",R4Wheel ="+tfreg4wheel.getText()+""
                + ",TypeOfDomAnimalWithNo = '"+domanimals+"',TypeOfPetAnimalWithNo = '"+pet+"',Bicycle = "+bike+",TNoCommVeh = "+commvehicle.getValue()+",ParkingFact = '"+parking+"', Lift = "+tflift.getText()+""
                + ",Escalator = "+tfescalator.getText()+",Helipad = "+tfhelipad.getText()+", Expectation = '"+taexpectation.getText()+"' WHERE HL_SNo = "+hlsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.dispose();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        bike = jcb.getSelectedIndex();
    }//GEN-LAST:event_jcbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHLOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHLOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHLOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHLOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHLOther dialog = new PbtHLOther(new PbtHouselisting(0, new PbtLoginData()), 0);
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndom;
    private javax.swing.JButton btnpet;
    private javax.swing.JButton btnsave;
    private javax.swing.JSpinner commvehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JRadioButton parkingno;
    private javax.swing.JRadioButton parkingyes;
    private javax.swing.JTextArea tadom;
    private javax.swing.JTextArea taexpectation;
    private javax.swing.JLabel tf;
    private javax.swing.JTextField tfescalator;
    private javax.swing.JTextField tfhelipad;
    private javax.swing.JTextField tflift;
    private javax.swing.JTextField tfpetno;
    private javax.swing.JTextField tfprotectedtrees;
    private javax.swing.JTextField tfreg2wheel;
    private javax.swing.JTextField tfreg4wheel;
    private javax.swing.JTextField tftrees;
    // End of variables declaration//GEN-END:variables
}
