/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;
import javax.swing.ButtonGroup;
/**
 *
 * @author rishu
 */
public class PbtHouseUse extends javax.swing.JDialog {

    PbtLoginData oblogin;
    PbtEnumDashboard enumdash;
    ButtonGroup bg;
    ParabitDBC db;
    int n;
    public PbtHouseUse(PbtEnumDashboard nob, PbtLoginData ob) {
        super(nob, true);
        setTitle("House Use");
        initComponents();
        this.setLocationRelativeTo(nob);
        bg = new ButtonGroup();
        bg.add(btnresidence);
        bg.add(btnresother);
        bg.add(btnshop);
        bg.add(btnschool);
        bg.add(btnhotel);
        bg.add(btnhospital);
        bg.add(btnworship);
        bg.add(btnfactory);
        bg.add(btnnonresidential);
        bg.add(btnvacant);
        oblogin = ob;
        enumdash = nob;
        db = new ParabitDBC();
        btnexit.setEnabled(false);
        btnproceed.setEnabled(false);
    }

    private int checkPending()
    {
        String latilongi = tflatitude.getText() + " , " + tflongitude.getText();
        String qry = "SELECT HL_SNo FROM pbtcensus_houselisting WHERE latilongi = '" + latilongi + "' AND Status = '8'";
        try
        {
            db.rs2 = db.stm.executeQuery(qry);
            if (db.rs2.next())
            {
                return db.rs2.getInt(1);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnresother = new javax.swing.JToggleButton();
        btnhospital = new javax.swing.JToggleButton();
        btnfactory = new javax.swing.JToggleButton();
        btnschool = new javax.swing.JToggleButton();
        btnhotel = new javax.swing.JToggleButton();
        btnshop = new javax.swing.JToggleButton();
        btnresidence = new javax.swing.JToggleButton();
        btnworship = new javax.swing.JToggleButton();
        btnvacant = new javax.swing.JToggleButton();
        btnnonresidential = new javax.swing.JToggleButton();
        btnproceed = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfcomment = new javax.swing.JTextField();
        tfmob = new javax.swing.JTextField();
        tflatitude = new javax.swing.JTextField();
        tflongitude = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnresother.setText("Residence-cum-other use");
        btnresother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresotherActionPerformed(evt);
            }
        });

        btnhospital.setText("Hospital/Dispensary");
        btnhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhospitalActionPerformed(evt);
            }
        });

        btnfactory.setText("Factory/Workshop/Workshed");
        btnfactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactoryActionPerformed(evt);
            }
        });

        btnschool.setText("School/College");
        btnschool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnschoolActionPerformed(evt);
            }
        });

        btnhotel.setText("Hotel/Lodge/Guest house");
        btnhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhotelActionPerformed(evt);
            }
        });

        btnshop.setText("Shop/Office");
        btnshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshopActionPerformed(evt);
            }
        });

        btnresidence.setText("Residence");
        btnresidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresidenceActionPerformed(evt);
            }
        });

        btnworship.setText("Place of worship");
        btnworship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnworshipActionPerformed(evt);
            }
        });

        btnvacant.setText("Vacant");
        btnvacant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvacantActionPerformed(evt);
            }
        });

        btnnonresidential.setText("Other non-residential use");
        btnnonresidential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnonresidentialActionPerformed(evt);
            }
        });

        btnproceed.setText("Save and Proceed");
        btnproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproceedActionPerformed(evt);
            }
        });

        btnexit.setText("Save and Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setText("Latitude:");

        jLabel2.setText("Mobile:");

        jLabel3.setText("Comment:");

        jLabel4.setText("Longitude:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnresidence, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnresother, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfactory, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tflatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tflongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfmob, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnworship, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnnonresidential, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnshop, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnschool, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnvacant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnproceed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tflatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfmob, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tflongitude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnresidence, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnresother, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnshop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnschool, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfactory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnworship, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnonresidential, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnvacant, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproceed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproceedActionPerformed
        int hlsno = checkPending();
        if (hlsno == 0)
        {
            String latilongi = tflatitude.getText() + " , " + tflongitude.getText();
            String qry = "INSERT INTO pbtcensus_houselisting (UseOfHouse, OwnerPhnNo, LatiLongi) VALUES('"+btnresidence.getText()+"','"+tfmob.getText()+"','"+latilongi+"')";
            String qry2 = "SELECT HL_SNo FROM pbtcensus_houselisting ORDER BY HL_SNo DESC LIMIT 1";

            try
            {
                db.stm.executeUpdate(qry);
                db.rs1 = db.stm.executeQuery(qry2);
                db.rs1.next();
                hlsno = db.rs1.getInt(1);
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        PbtHouseType ob = new PbtHouseType(enumdash, oblogin, hlsno);
        ob.n = n;
        new PbtUseOfHouse(n);
        ob.visible();
        this.dispose();
        ob.setVisible(true);
            
    }//GEN-LAST:event_btnproceedActionPerformed

    private void btnresotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresotherActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnresotherActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int hlsno = 0;
        String latilongi = tflatitude.getText() + " , " + tflongitude.getText();
        String qry = "INSERT INTO pbtcensus_houselisting (UseOfHouse, OwnerPhnNo, LatiLongi, Status) VALUES('"+btnresidence.getText()+"','"+tfmob.getText()+"','"+latilongi+"', '8')";
        String qry2 = "SELECT HL_SNo FROM pbtcensus_houselisting ORDER BY HL_SNo DESC LIMIT 1";

        try
        {
            db.stm.executeUpdate(qry);
            db.rs1 = db.stm.executeQuery(qry2);
            db.rs1.next();
            hlsno = db.rs1.getInt(1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        this.dispose();
        enumdash.setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnresidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresidenceActionPerformed
        if (!tflatitude.getText().isEmpty())
        {
            btnexit.setEnabled(true);
            btnproceed.setEnabled(true);
        }
        n = 1;
    }//GEN-LAST:event_btnresidenceActionPerformed

    private void btnshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshopActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnshopActionPerformed

    private void btnschoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnschoolActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnschoolActionPerformed

    private void btnhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhotelActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnhotelActionPerformed

    private void btnhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhospitalActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnhospitalActionPerformed

    private void btnfactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactoryActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnfactoryActionPerformed

    private void btnworshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnworshipActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
        n = 8;
    }//GEN-LAST:event_btnworshipActionPerformed

    private void btnnonresidentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnonresidentialActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnnonresidentialActionPerformed

    private void btnvacantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvacantActionPerformed
        btnexit.setEnabled(true);
        btnproceed.setEnabled(true);
    }//GEN-LAST:event_btnvacantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHouseUse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHouseUse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHouseUse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHouseUse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PbtHouseUse dialog = new PbtHouseUse(new PbtEnumDashboard(new PbtLoginData()), new PbtLoginData());
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JToggleButton btnfactory;
    private javax.swing.JToggleButton btnhospital;
    private javax.swing.JToggleButton btnhotel;
    private javax.swing.JToggleButton btnnonresidential;
    private javax.swing.JButton btnproceed;
    private javax.swing.JToggleButton btnresidence;
    private javax.swing.JToggleButton btnresother;
    private javax.swing.JToggleButton btnschool;
    private javax.swing.JToggleButton btnshop;
    private javax.swing.JToggleButton btnvacant;
    private javax.swing.JToggleButton btnworship;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfcomment;
    private javax.swing.JTextField tflatitude;
    private javax.swing.JTextField tflongitude;
    private javax.swing.JTextField tfmob;
    // End of variables declaration//GEN-END:variables
}
