/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;
import javax.swing.ButtonGroup;
/**
 *
 * @author rishu
 */
public class PbtOtherDetails extends javax.swing.JDialog {

    PbtAadharDetails aadharob;
    ParabitDBC db;
    PbtPersonDashboard obperson;
    ButtonGroup bg1, bg2, bg3, bg4, bg5;
    String hinsu, linsu, foreigndispute, courtcase, fincase;
    int hhsno;
    public PbtOtherDetails(PbtPersonDashboard ob, PbtAadharDetails nob, int hhno, boolean in) {
        super(ob, true);
        setTitle("Other Details");
        initComponents();
        hhsno = hhno;
        aadharob = nob;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg3 = new ButtonGroup();
        bg4 = new ButtonGroup();
        bg5 = new ButtonGroup();
        bg1.add(liyes);
        bg1.add(lino);
        bg2.add(hiyes);
        bg2.add(hino);
        bg3.add(ccaseyes);
        bg3.add(ccaseno);
        bg4.add(fdispyes);
        bg4.add(fdispno);
        bg5.add(fincaseyes);
        bg5.add(fincaseno);
        
        if (in == true)
        {
            incomp();
        }
    }
    
    public PbtOtherDetails(PbtPersonDashboard ob, int hhno, boolean in) {
        super(ob, true);
        setTitle("Other Details");
        initComponents();
        hhsno = hhno;
        obperson = ob;
        db = new ParabitDBC();
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg3 = new ButtonGroup();
        bg4 = new ButtonGroup();
        bg5 = new ButtonGroup();
        bg1.add(liyes);
        bg1.add(lino);
        bg2.add(hiyes);
        bg2.add(hino);
        bg3.add(ccaseyes);
        bg3.add(ccaseno);
        bg4.add(fdispyes);
        bg4.add(fdispno);
        bg5.add(fincaseyes);
        bg5.add(fincaseno);
        
        if (in == true)
        {
            incomp();
        }
    }
    
    public void incomp()
    {
        try
        {
            tfchildsurvived.setText(obperson.db.rs2.getString("ChdnSurv"));
            tfchildreneverborn.setText(obperson.db.rs2.getString("ChdnEvenBorn"));
            tfnoofchildalive.setText(obperson.db.rs2.getString("NoOfChdnAliveLastYr"));
            tfrsnofmig.setText(obperson.db.rs2.getString("RsnOfMig"));
            tfdurofmig.setText(obperson.db.rs2.getString("DurOfMig"));
            if (obperson.db.rs2.getString("L_Insu").equals("Y"))
            {
                liyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("L_Insu").equals("N"))
            {
                lino.setSelected(true);
            }
            
            if (obperson.db.rs2.getString("H_Insu").equals("Y"))
            {
                hiyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("H_Insu").equals("N"))
            {
                hino.setSelected(true);
            }
            
            if (obperson.db.rs2.getString("CourtCase").equals("Y"))
            {
                ccaseyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("CourtCase").equals("N"))
            {
                ccaseno.setSelected(true);
            }
            
            if (obperson.db.rs2.getString("FinCase").equals("Y"))
            {
                fincaseyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("FinCase").equals("N"))
            {
                fincaseno.setSelected(true);
            }
            
            if (obperson.db.rs2.getString("ForeignDispute").equals("Y"))
            {
                fdispyes.setSelected(true);
            }
            else if (obperson.db.rs2.getString("ForeignDispute").equals("N"))
            {
                fdispno.setSelected(true);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tfchildreneverborn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfnoofchildalive = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfchildsurvived = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfrsnofmig = new javax.swing.JTextField();
        tfdurofmig = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        liyes = new javax.swing.JRadioButton();
        lino = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        hiyes = new javax.swing.JRadioButton();
        hino = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        ccaseyes = new javax.swing.JRadioButton();
        ccaseno = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        fincaseyes = new javax.swing.JRadioButton();
        fincaseno = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        fdispyes = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        fdispno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel17.setText("Children Even Born:");

        jLabel18.setText("No. Of Children Alive Last Year:");

        jLabel1.setText("Other Details:");

        jLabel5.setText("Children Survived:");

        jLabel7.setText("Reason of Migration:");

        jLabel8.setText("Duration of Migration:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        liyes.setText("Yes");

        lino.setText("No");

        jLabel16.setText("Life Insurance:");

        hiyes.setText("Yes");

        hino.setText("No");

        jLabel19.setText("Health Insurance:");

        ccaseyes.setText("Yes");

        ccaseno.setText("No");

        jLabel24.setText("Court Case:");

        fincaseyes.setText("Yes");

        fincaseno.setText("No");

        jLabel25.setText("Financial Case:");

        fdispyes.setText("Yes");

        jLabel26.setText("Foreign Dispute:");

        fdispno.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(tfchildreneverborn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(21, 21, 21)
                                .addComponent(tfnoofchildalive, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(fdispyes)
                                .addGap(8, 8, 8)
                                .addComponent(fdispno))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfchildsurvived, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfrsnofmig, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfdurofmig, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(liyes)
                                    .addGap(8, 8, 8)
                                    .addComponent(lino)
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(hiyes)
                                    .addGap(8, 8, 8)
                                    .addComponent(hino))))
                        .addGap(0, 47, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(ccaseyes)
                .addGap(8, 8, 8)
                .addComponent(ccaseno)
                .addGap(60, 60, 60)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(fincaseyes)
                .addGap(18, 18, 18)
                .addComponent(fincaseno)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfchildsurvived, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfchildreneverborn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfnoofchildalive, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfrsnofmig, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdurofmig, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(liyes)
                            .addComponent(lino)
                            .addComponent(hiyes)
                            .addComponent(hino))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fincaseyes)
                                .addComponent(fincaseno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ccaseyes)
                                    .addComponent(ccaseno))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fdispyes)
                                    .addComponent(fdispno))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if (hiyes.isSelected())
        {
            hinsu = "Y";
        }
        else
        {
            hinsu = "N";
        }
        if (liyes.isSelected())
        {
            linsu = "Y";
        }
        else
        {
            linsu = "N";
        }
        if (ccaseyes.isSelected())
        {
            courtcase = "Y";
        }
        else
        {
            courtcase = "N";
        }
        if (fincaseyes.isSelected())
        {
            fincase = "Y";
        }
        else
        {
            fincase = "N";
        }
        if (fdispyes.isSelected())
        {
            foreigndispute = "Y";
        }
        else
        {
            foreigndispute = "N";
        }
        
        String qry = "UPDATE pbtcensus_household SET ChdnSurv = '"+tfchildsurvived.getText()+"',ChdnEvenBorn = '"+tfchildreneverborn.getText()+"',NoOfChdnAliveLastYr = '"+tfnoofchildalive.getText()+"',"
                + "RsnOfMig = '"+tfrsnofmig.getText()+"',DurOfMig = '"+tfdurofmig.getText()+"',H_Insu = '"+hinsu+"',L_Insu = '"+linsu+"',CourtCase = '"+courtcase+"',ForeignDispute = '"+foreigndispute+"',FinCase = '"+fincase+"' WHERE HH_SNo = "+hhsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.dispose();
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtOtherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtOtherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtOtherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtOtherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHomedashboard obj = new PbtHomedashboard(0, new PbtLoginData());
                PbtOtherDetails dialog = new PbtOtherDetails(new PbtPersonDashboard(obj, 2), 2, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ccaseno;
    private javax.swing.JRadioButton ccaseyes;
    private javax.swing.JRadioButton fdispno;
    private javax.swing.JRadioButton fdispyes;
    private javax.swing.JRadioButton fincaseno;
    private javax.swing.JRadioButton fincaseyes;
    private javax.swing.JRadioButton hino;
    private javax.swing.JRadioButton hiyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton lino;
    private javax.swing.JRadioButton liyes;
    private javax.swing.JTextField tfchildreneverborn;
    private javax.swing.JTextField tfchildsurvived;
    private javax.swing.JTextField tfdurofmig;
    private javax.swing.JTextField tfnoofchildalive;
    private javax.swing.JTextField tfrsnofmig;
    // End of variables declaration//GEN-END:variables
}
