/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author rishu
 */
public class PbtPersonDashboard extends javax.swing.JFrame {
    boolean adhr, incomplete;
    int f, hhsno, hlsno;
    ParabitDBC db, db1;
    PbtAadharDetails aadharob;
    PbtIncompleteCensus obinc;
    PbtHomedashboard obdash;
    String[] values;
    String mob;
    public PbtPersonDashboard(PbtHomedashboard ob, int hlno) {
        setTitle("");
        initComponents();
        db = new ParabitDBC();
        db1 = new ParabitDBC(1);
        values = new String[14];
        incomplete = false; // is incomplete // status 7
        adhr = true;   //have adhar in db
        f = 0;   //no scan aadhar
        hlsno = hlno;
        obdash = ob;
        btnbasic.setEnabled(false);
        btnmedical.setEnabled(false);
        btneducation.setEnabled(false);
        btnwork.setEnabled(false);
        btnhappiness.setEnabled(false);
        btnbank.setEnabled(false);
        btnothers.setEnabled(false);
        btnsave.setVisible(false);
    }
    
    public PbtPersonDashboard(PbtIncompleteCensus ob, int hhno)  //for incomplete census
    {
        initComponents();
        btnok.setVisible(false);
        btnsaveback.setVisible(false);
        hhsno = hhno;
        db = new ParabitDBC();
        db1 = new ParabitDBC(1);
        values = new String[14];
        obinc = ob;
        adhr = true;
        String qry = "SELECT * FROM pbtcensus_household WHERE HH_SNo = " + hhno;
        try
        {
            db.rs2 = db.stm.executeQuery(qry);
            db.rs2.next();
            tfaadhar.setText(db.rs2.getString("UID"));
            tfname.setText(db.rs2.getString("Name"));
            tfpassport.setText(db.rs2.getString("Passport"));
            tfpan.setText(db.rs2.getString("PanCardNo"));
            tfvoter.setText(db.rs2.getString("VID"));
            tfration.setText(db.rs2.getString("RCardNo"));
            tfrcardtype.setText(db.rs2.getString("RCardType"));
            tfarms.setText(db.rs2.getString("ArmsUINo"));
            tfbirth.setText(db.rs2.getString("BirthCertNo"));
            tfpolver.setText(db.rs2.getString("PoliceVerNo"));
            tfmarriage.setText(db.rs2.getString("MarrCertNo"));
            tfdisability.setText(db.rs2.getString("PWDID"));
            tfdl.setText(db.rs2.getString("DrivLicNo"));
            tfgas.setText(db.rs2.getString("GConsumerNo"));
            tfpension.setText(db.rs2.getString("PensionID"));
            tfsssmid.setText(db.rs2.getString("SSSMID"));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        incomplete = true;
        checkAadhar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfaadhar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfpassport = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfvoter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnhappiness = new javax.swing.JButton();
        btneducation = new javax.swing.JButton();
        btnothers = new javax.swing.JButton();
        btnbank = new javax.swing.JButton();
        btnwork = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        btnscan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfpan = new javax.swing.JTextField();
        btnbasic = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfration = new javax.swing.JTextField();
        tfdl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfgas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfpolver = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfpension = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfarms = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfdisability = new javax.swing.JTextField();
        btnmedical = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfrcardtype = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfbirth = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfmarriage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfsssmid = new javax.swing.JTextField();
        btnsaveback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aadhar:");

        jLabel2.setText("Name:");

        jLabel3.setText("Passport No.:");

        jLabel4.setText("Pan No.:");

        btnhappiness.setText("Happiness");
        btnhappiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhappinessActionPerformed(evt);
            }
        });

        btneducation.setText("Education Details");
        btneducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneducationActionPerformed(evt);
            }
        });

        btnothers.setText("others");
        btnothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnothersActionPerformed(evt);
            }
        });

        btnbank.setText("Bank Details");
        btnbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbankActionPerformed(evt);
            }
        });

        btnwork.setText("Work Details");
        btnwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnworkActionPerformed(evt);
            }
        });

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btnscan.setText("Scan");
        btnscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnscanActionPerformed(evt);
            }
        });

        jLabel5.setText("Voter ID:");

        btnbasic.setText("Basic Details");
        btnbasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbasicActionPerformed(evt);
            }
        });

        jLabel6.setText("Gas No.:");

        jLabel7.setText("Ration ID:");

        jLabel8.setText("Driving Liscence No.:");

        jLabel9.setText("Police Verification No.:");

        jLabel10.setText("Pension ID:");

        jLabel11.setText("Arms UI No.:");

        jLabel13.setText("Disability Reg No.:");

        btnmedical.setText("Medical Details");
        btnmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicalActionPerformed(evt);
            }
        });

        jLabel12.setText("Birth Certificate No.:");

        jLabel14.setText("Marriage Certificate No.:");

        jLabel15.setText("Ration Card Type:");

        jLabel16.setText("SSSMID:");

        btnsaveback.setText("Save and Back");
        btnsaveback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavebackActionPerformed(evt);
            }
        });

        btnsave.setText("Save and Exit");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnscan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsaveback, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(tfpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfpan, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tfvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tfration, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30)
                        .addComponent(tfrcardtype, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tfarms, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(tfbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfpolver, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(tfmarriage, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(tfdisability, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(tfdl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfgas, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(tfpension, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tfsssmid, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnbank, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnothers, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnhappiness, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnbasic, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btneducation, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnwork, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnscan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsaveback, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfrcardtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfarms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmarriage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdisability, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfgas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpension, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16))
                    .addComponent(tfsssmid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbasic, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneducation, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnwork, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnbank, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnothers, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhappiness, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnscanActionPerformed
        if (tfaadhar.getText().equals(""))
        {
            /*PbtQrCapture cap = new PbtQrCapture();
            cap.setVisible(true);*/
            final Thread thread = new Thread(new Runnable() {



					@Override

					public void run() {

						try (PbtQrCapture qr = new PbtQrCapture()) {

							aadharDet("QR code text is:\n" + qr.getResult()  + "");

						} catch (InterruptedException ex) {

							ex.printStackTrace();

						}

					};

				});

				thread.setDaemon(true);

				thread.start();
                                f =1;  //aadhar scan
                                
        }
        checkAadhar();

        
    }//GEN-LAST:event_btnscanActionPerformed

    public void checkAadhar()
    {
        String aadhar = tfaadhar.getText();
        //String qry = "INSERT INTO pbtcensus_household (UID) Values ('"+aadhar+"')";
        String qry2 = "select a.*, pan.PanNo, arms.UIN, dl.DLNumber, pass.PassNo, voter.VID, police.PolVerNu, ration.RtnID, gas.CosNo, pension.PIDNo, disable.RegNo from pbtaadhar a "
                + "left join pbtpan pan on a.ANo = pan.AdhrNo left join pbtarmslicense arms on a.ANo = arms.AadhNo left join pbtdl dl on a.ANo = dl.AdhrNo left join pbtpass pass on a.ANo = pass.ANo"
                + " left join pbtvid voter on a.ANo = voter.Ano left join pbt_police_ver police on a.ANo = police.AadNo left join pbt_rationcarddata ration on a.ANo = ration.AdhrNo "
                + " left join pbtgas gas on a.ANo = gas.AadNo left join pbtpension pension on a.ANo = pension.ANo left join pbtdisability disable on a.ANo = disable.Ano WHERE a.ANo = '"+aadhar+"'";
        System.out.println(qry2);
        System.out.println(f);
        try
        {
            db1.rs1 = db1.stm.executeQuery(qry2);
            if(db1.rs1.next())
            {
                tfname.setText(db1.rs1.getString("FstName")+ " "+db1.rs1.getString("MidName")+" "+db1.rs1.getString("LstName"));
                String nm = tfname.getText();
                if (f == 0)
                {
                    values[0] = aadhar;
                    values[1] = nm;
                    values[2] = db1.rs1.getString("Gender");
                    values[3] = db1.rs1.getString("DOB");
                    values[4] = "";
                    //values[4] = db1.rs1.getString("FstName"); //careOf
                    values[5] = db1.rs1.getString("HNo");
                    values[6] = db1.rs1.getString("SRL");
                    values[7] = db1.rs1.getString("LMrk");
                    values[8] = db1.rs1.getString("VTC");
                    values[9] = db1.rs1.getString("PO");
                    values[10] = db1.rs1.getString("District");
                    values[11] = db1.rs1.getString("Tehsil");
                    values[12] = db1.rs1.getString("State");
                    values[13] = db1.rs1.getString("PIN");
                    aadharob = new PbtAadharDetails(values);
                }
            
                tfpassport.setText(db1.rs1.getString("PassNo"));
                tfpan.setText(db1.rs1.getString("PanNo"));
                tfvoter.setText(db1.rs1.getString("VID"));
                tfration.setText(db1.rs1.getString("RtnID"));
                tfdl.setText(db1.rs1.getString("DLNumber"));
                tfpolver.setText(db1.rs1.getString("PolVerNu"));
                tfarms.setText(db1.rs1.getString("UIN"));
            }
            else
            {
                System.out.println("NO AADHAR IN DB");
                adhr = false;
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    private void btnbasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbasicActionPerformed
        if (adhr == true)
        {
            PbtBasicDetails ob = new PbtBasicDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtBasicDetails ob;
            ob = new PbtBasicDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
            
        }  
    }//GEN-LAST:event_btnbasicActionPerformed

    private void btneducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneducationActionPerformed
        if (adhr == true)
        {
            PbtEducationDetails ob = new PbtEducationDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtEducationDetails ob;
            ob = new PbtEducationDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_btneducationActionPerformed

    private void btnhappinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhappinessActionPerformed
        PbtHappinessDetails ob = new PbtHappinessDetails(this, hhsno, incomplete);
        ob.setLocationRelativeTo(this);
        ob.setVisible(true);
    }//GEN-LAST:event_btnhappinessActionPerformed

    private void btnworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnworkActionPerformed
        if (adhr == true)
        {
            PbtWorkDetails ob = new PbtWorkDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtWorkDetails ob;
            ob = new PbtWorkDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_btnworkActionPerformed

    private void btnbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbankActionPerformed
        if (adhr == true)
        {
            PbtBankDetails ob = new PbtBankDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtBankDetails ob;
            ob = new PbtBankDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_btnbankActionPerformed

    private void btnothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnothersActionPerformed
        if (adhr == true)
        {
            PbtOtherDetails ob = new PbtOtherDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtOtherDetails ob;
            ob = new PbtOtherDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_btnothersActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        String qry = "INSERT INTO pbtcensus_household (HL_SNo, UID, Name, Passport, PanCardNo, VID, RCardNo, DrivLicNo, PoliceVerNo, GConsumerNo,"
                + " ArmsUINo, PensionID, PWDID, BirthCertNo, RCardType, MarrCertNo, SSSMID) VALUES('"+hlsno+"','"+tfaadhar.getText()+"','"+tfname.getText()+"','"+tfpassport.getText()+"','"+tfpan.getText()+"',"
                + "'"+tfvoter.getText()+"','"+tfration.getText()+"','"+tfdl.getText()+"','"+tfpolver.getText()+"','"+tfgas.getText()+"',"
                + "'"+tfarms.getText()+"','"+tfpension.getText()+"','"+tfdisability.getText()+"','"+tfbirth.getText()+"','"+tfrcardtype.getText()+"','"+tfmarriage.getText()+"','"+tfsssmid.getText()+"')";
        String qry2 = "SELECT HH_SNo FROM pbtcensus_household ORDER BY HL_SNo DESC LIMIT 1";
        try
        {
            db.stm.executeUpdate(qry);
            db.rs1 = db.stm.executeQuery(qry2);
            db.rs1.next();
            hhsno = db.rs1.getInt(1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        btnbasic.setEnabled(true);
        btnmedical.setEnabled(true);
        btneducation.setEnabled(true);
        btnwork.setEnabled(true);
        btnhappiness.setEnabled(true);
        btnbank.setEnabled(true);
        btnothers.setEnabled(true);
        btnok.setEnabled(false);
    }//GEN-LAST:event_btnokActionPerformed

    private void btnmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicalActionPerformed
        if (adhr == true)
        {
            PbtMedicalDetails ob = new PbtMedicalDetails(this, aadharob, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
        else
        {
            System.out.println(hhsno);
            PbtMedicalDetails ob;
            ob = new PbtMedicalDetails(this, hhsno, incomplete);
            ob.setLocationRelativeTo(this);
            ob.setVisible(true);
        }
    }//GEN-LAST:event_btnmedicalActionPerformed

    private void btnsavebackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavebackActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Form Completed...?", "Select", 0) == 0)
        {
            obdash.comp = "Y";
        }
        else
        {
            obdash.comp = "N";
        }
        obdash.hhno = hhsno;
        obdash.aadhar = tfaadhar.getText();
        obdash.name = tfname.getText();
        obdash.mob = mob;
        obdash.setTable();
        this.dispose();
    }//GEN-LAST:event_btnsavebackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String qry = "UPDATE pbtcensus_household SET UID = '"+tfaadhar.getText()+"', Name = '"+tfname.getText()+"', Passport = '"+tfpassport.getText()+"', PanCardNo = '"+tfpan.getText()+"', VID = '"+tfvoter.getText()+"'"
                + ", RCardNo = '"+tfration.getText()+"', DrivLicNo = '"+tfdl.getText()+"', PoliceVerNo = '"+tfpolver.getText()+"', GConsumerNo = '"+tfgas.getText()+"', ArmsUINo = '"+tfarms.getText()+"', PensionID = '"+tfpension.getText()+"'"
                + " , PWDID = '"+tfdisability.getText()+"', BirthCertNo = '"+tfbirth.getText()+"', RCardType = '"+tfrcardtype.getText()+"', MarrCertNo = '"+tfmarriage.getText()+"', SSSMID = '"+tfsssmid.getText()+"', Status = '1' WHERE HH_SNo = "+hhsno;
        System.out.println(qry);
        try
        {
            db.stm.executeUpdate(qry);
            db.rs3 = db.stm.executeQuery("SELECT WorkDone From pbtempschedule WHERE CEID = '"+PbtLoginData.ceid+"' AND City_Vill = '"+PbtLoginData.town+"'");
            db.rs3.next();
            int wd = db.rs3.getInt(1) + 1;
            db.stm.executeUpdate("UPDATE pbtempschedule SET WorkDone = "+wd+" WHERE CEID = '"+PbtLoginData.ceid+"' AND City_Vill = '"+PbtLoginData.town+"'");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Saved Successfully!!!");
        this.setVisible(false);
        obinc.loadTable();
        obinc.setVisible(true);
        
    }//GEN-LAST:event_btnsaveActionPerformed

 private void aadharDet(String text)
        {
            String ar[] = {"uid", "name", "gender", "dateOfBirth", "careOf", "building", "street", "landmark", "vtcName", "poName", "districtName", "subDistrictName", "stateName", "pincode"};
            Pattern p;
            Matcher m;
            System.out.println(text);
            for (int i = 0; i < ar.length; i++)
            {
                p = Pattern.compile(ar[i] + "=\"(.[^\"]*)\"");
                m = p.matcher(text);
                if (m.find())
                {
                    System.out.println(ar[i] + " = " + m.group(1));
                    values[i] = m.group(1);
                    /*if (i == 0)
                    {
                        tfaadhar.setText(m.group(1));
                    }*/
                }
            }
            for (int i = 0; i <values.length; i++)
            {
                System.out.println(values[i]);
            }
            tfaadhar.setText(values[0]);
            tfname.setText(values[1]);
            aadharob = new PbtAadharDetails(values, 1);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtPersonDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtPersonDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtPersonDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtPersonDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtHomedashboard obj = new PbtHomedashboard(0, new PbtLoginData());
                PbtPersonDashboard ob = new PbtPersonDashboard(obj, 0);
                ob.setLocationRelativeTo(null);
                ob.setVisible(true);*/
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbank;
    private javax.swing.JButton btnbasic;
    private javax.swing.JButton btneducation;
    javax.swing.JButton btnhappiness;
    private javax.swing.JButton btnmedical;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnothers;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsaveback;
    private javax.swing.JButton btnscan;
    private javax.swing.JButton btnwork;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfaadhar;
    private javax.swing.JTextField tfarms;
    private javax.swing.JTextField tfbirth;
    private javax.swing.JTextField tfdisability;
    private javax.swing.JTextField tfdl;
    private javax.swing.JTextField tfgas;
    private javax.swing.JTextField tfmarriage;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfpan;
    private javax.swing.JTextField tfpassport;
    private javax.swing.JTextField tfpension;
    private javax.swing.JTextField tfpolver;
    private javax.swing.JTextField tfration;
    private javax.swing.JTextField tfrcardtype;
    private javax.swing.JTextField tfsssmid;
    private javax.swing.JTextField tfvoter;
    // End of variables declaration//GEN-END:variables
}
