/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

/**
 *
 * @author rishu
 */
public class PbtPC extends javax.swing.JDialog {

    int pc;
    PbtHLAppliance obapp;
    public PbtPC(PbtHLAppliance ob) {
        super(ob, true);
        setTitle("PC");
        initComponents();
        obapp = ob;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        b2 = new javax.swing.JToggleButton();
        b1 = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        b11 = new javax.swing.JToggleButton();
        b16 = new javax.swing.JToggleButton();
        b21 = new javax.swing.JToggleButton();
        b8 = new javax.swing.JToggleButton();
        b7 = new javax.swing.JToggleButton();
        b10 = new javax.swing.JToggleButton();
        b9 = new javax.swing.JToggleButton();
        b13 = new javax.swing.JToggleButton();
        b12 = new javax.swing.JToggleButton();
        b15 = new javax.swing.JToggleButton();
        b14 = new javax.swing.JToggleButton();
        b18 = new javax.swing.JToggleButton();
        b17 = new javax.swing.JToggleButton();
        b20 = new javax.swing.JToggleButton();
        b19 = new javax.swing.JToggleButton();
        b23 = new javax.swing.JToggleButton();
        b22 = new javax.swing.JToggleButton();
        b25 = new javax.swing.JToggleButton();
        b24 = new javax.swing.JToggleButton();
        b28 = new javax.swing.JToggleButton();
        b27 = new javax.swing.JToggleButton();
        b30 = new javax.swing.JToggleButton();
        b29 = new javax.swing.JToggleButton();
        b26 = new javax.swing.JToggleButton();
        btnok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(b2);
        b2.setText("Desktop");

        buttonGroup1.add(b1);
        b1.setText("Laptop");

        buttonGroup1.add(b3);
        b3.setText("Tablet");

        buttonGroup1.add(b4);
        b4.setText("Pocket PC");

        buttonGroup1.add(b5);
        b5.setText("Utra Mobile PC");

        buttonGroup1.add(b6);
        b6.setText("Laptop,Desktop");

        buttonGroup1.add(b11);
        b11.setText("Desktop,PocketPC");

        buttonGroup1.add(b16);
        b16.setText("Laptop,Desktop,Tablet");

        buttonGroup1.add(b21);
        b21.setText("Laptop,PocketPC,Ultra Mobile PC");

        buttonGroup1.add(b8);
        b8.setText("Laptop,PocketPC");

        buttonGroup1.add(b7);
        b7.setText("Laptop,Tablet");

        buttonGroup1.add(b10);
        b10.setText("Desktop,Tablet");

        buttonGroup1.add(b9);
        b9.setText("Laptop,Ultra mobile PC");

        buttonGroup1.add(b13);
        b13.setText("Tablet,Ultra Mobile PC");

        buttonGroup1.add(b12);
        b12.setText("Desktop,Ultra Mobile PC");

        buttonGroup1.add(b15);
        b15.setText("Pocket PC,Ultra Mobile PC");

        buttonGroup1.add(b14);
        b14.setText("Tablet,Pocket PC");

        buttonGroup1.add(b18);
        b18.setText("Laptop,Desktop,Ultr Mobile PC");

        buttonGroup1.add(b17);
        b17.setText("Laptop,Desktop,PocketPC");

        buttonGroup1.add(b20);
        b20.setText("Laptop,Tablet,Ultra Mobile PC");

        buttonGroup1.add(b19);
        b19.setText("Laptop,Tablet,PocketPC");

        buttonGroup1.add(b23);
        b23.setText("Desktop,Tablet,Ultra Mobile PC");

        buttonGroup1.add(b22);
        b22.setText("Desktop,Tablet,PocketPC");

        buttonGroup1.add(b25);
        b25.setText("Tablet,PocketPC,Ultra Mobile PC");
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        buttonGroup1.add(b24);
        b24.setText("Desktop,PocketPC,Ultra Mobile PC");

        buttonGroup1.add(b28);
        b28.setText("Laptop,Tablet,PocketPC,Ultra Mobile PC");

        buttonGroup1.add(b27);
        b27.setText("Laptop,Desktop,Tablet,Ultra Mobile PC");

        buttonGroup1.add(b30);
        b30.setText("Desktop,Tablet,PocketPC,Ultra Mobile PC");
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(b29);
        b29.setText("Laptop,Desktop,PocketPC,Ultra Mobile PC");

        buttonGroup1.add(b26);
        b26.setText("Laptop,Desktop,Tablet,PocketPC");

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addComponent(b29)
                .addGap(74, 74, 74)
                .addComponent(b30)
                .addGap(134, 134, 134)
                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b13)))
                        .addGap(60, 60, 60)
                        .addComponent(b20)
                        .addGap(68, 68, 68)
                        .addComponent(b21)
                        .addGap(56, 56, 56)
                        .addComponent(b22)
                        .addGap(69, 69, 69)
                        .addComponent(b23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9)
                            .addComponent(b15))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b12)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b16)
                                .addGap(46, 46, 46)
                                .addComponent(b17)
                                .addGap(28, 28, 28)
                                .addComponent(b18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(b24)
                        .addGap(58, 58, 58)
                        .addComponent(b25)
                        .addGap(46, 46, 46)
                        .addComponent(b26)
                        .addGap(57, 57, 57)
                        .addComponent(b27)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b25ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b30ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
       if (b1.isSelected())
        {
            pc = 1;
        }
        if (b2.isSelected())
        {
            pc = 2;
        }
        if (b3.isSelected())
        {
            pc = 3;
        }
        if (b4.isSelected())
        {
            pc = 4;
        }
        if (b5.isSelected())
        {
            pc = 5;
        }
        if (b6.isSelected())
        {
            pc = 6;
        }
        if (b7.isSelected())
        {
            pc = 7;
        }
        if (b8.isSelected())
        {
            pc = 8;
        }
        if (b9.isSelected())
        {
            pc = 9;
        }
        if (b10.isSelected())
        {
            pc = 10;
        }
        if (b11.isSelected())
        {
            pc = 11;
        }
        if (b12.isSelected())
        {
            pc = 12;
        }
        if (b13.isSelected())
        {
            pc = 13;
        }
        if (b14.isSelected())
        {
            pc = 14;
        }
        if (b15.isSelected())
        {
            pc = 15;
        }
        if (b16.isSelected())
        {
            pc = 16;
        }
        if (b17.isSelected())
        {
            pc = 17;
        }
        if (b18.isSelected())
        {
            pc = 18;
        }
        if (b19.isSelected())
        {
            pc = 19;
        }
        if (b20.isSelected())
        {
            pc = 20;
        }
        if (b21.isSelected())
        {
            pc = 21;
        }
        if (b22.isSelected())
        {
            pc = 22;
        }
        if (b23.isSelected())
        {
            pc = 23;
        }
        if (b24.isSelected())
        {
            pc = 24;
        }
        if (b25.isSelected())
        {
            pc = 25;
        }
        if (b26.isSelected())
        {
            pc = 26;
        }
        if (b27.isSelected())
        {
            pc = 27;
        }
        if (b28.isSelected())
        {
            pc = 28;
        }
        if (b29.isSelected())
        {
            pc = 29;
        }
        if (b30.isSelected())
        {
            pc = 30;
        }
        
        obapp.pc = pc;
        this.dispose();
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*PbtPC dialog = new PbtPC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b10;
    private javax.swing.JToggleButton b11;
    private javax.swing.JToggleButton b12;
    private javax.swing.JToggleButton b13;
    private javax.swing.JToggleButton b14;
    private javax.swing.JToggleButton b15;
    private javax.swing.JToggleButton b16;
    private javax.swing.JToggleButton b17;
    private javax.swing.JToggleButton b18;
    private javax.swing.JToggleButton b19;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton b20;
    private javax.swing.JToggleButton b21;
    private javax.swing.JToggleButton b22;
    private javax.swing.JToggleButton b23;
    private javax.swing.JToggleButton b24;
    private javax.swing.JToggleButton b25;
    private javax.swing.JToggleButton b26;
    private javax.swing.JToggleButton b27;
    private javax.swing.JToggleButton b28;
    private javax.swing.JToggleButton b29;
    private javax.swing.JToggleButton b3;
    private javax.swing.JToggleButton b30;
    private javax.swing.JToggleButton b4;
    private javax.swing.JToggleButton b5;
    private javax.swing.JToggleButton b6;
    private javax.swing.JToggleButton b7;
    private javax.swing.JToggleButton b8;
    private javax.swing.JToggleButton b9;
    private javax.swing.JButton btnok;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
